server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL}
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-management-service
        uri: lb://user-management-service
        predicates:
        - Path=/user-management/**
        filters:
        - RewritePath=/user-management/(?<path>.*), /$\{path}
      - id: immunization-portal-service
        uri: lb://immunization-portal-service
        predicates:
        - Path=/immunization-portal/**
        filters:
        - RewritePath=/immunization-portal/(?<path>.*), /$\{path}
      - id: mail-service
        uri: lb://mail-service
        predicates:
        - Path=/mail/**
        filters:
        - RewritePath=/mail/(?<path>.*), /$\{path}

springdoc:
  swagger-ui:
    urls:
      - name: user-management
        url: /v3/api-docs/user-management
      - name: immunization-portal
        url: /v3/api-docs/immunization-portal
      - name: mail
        url: /v3/api-docs/mail